sudo: false
language: java
jdk:
- oraclejdk8
deploy:
  provider: script
  script: "./gradlew release"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
    secure: LGKoi5zNA8sL2J9QtvSq+2MqoE656vrlUnXDPJhSvUn9zB+M8qOvyLezWF6nkknE2GpP85SNIc45Z3/rg/NSsq4d51WNyQc86VyjahLKk2m7U9cwulf/0lccZYaWJh2h4szV8o8BkniR6Q9IAt5lyV41gEdfgiU/2J+3TGWyZidWFmx7pJnH1MroU0OhcfaKHSH5do28q6yJqoN4oykXd3kcYT3N91QRBOd/NCtgdSChvX9E08DpgswVWiRDwQEmvWCPRkqVkBQwSeEdo2XYtrYxlFNy7LlQedjJGntuxqYfeazS1WBRbu9a6vuQztp8Qx+9KRgsyMgbRWlC/KFElheAf6YS0o4RjsEFCP+5kQYUgDH5VHt8F2K0/5zYil+rOtyA7sz03JqfIB2FjABaWM7TAdcufKre/lqf+DxH/z1BNqUXH9QfoxaPZqLS6KWvI6rsftE6rYfBkaR3GVjNfYHkfb+nDzXhCRjxo/ht0dm4M8ZNFDeNGai2of4L0StcJFSRSjWcH0AA6EuXEpkZYft+34siyUj0NevEv3W62m3iEJZOV9rUrXIOOf8BrnVGuseo+vokairOUlpu5FLSvkoKwbiWebT2uyasgM3Lu5ln4jtdMz2A/bTrlWA9/dg4YRx5GwJM7E9RRQfR6o9VaacHdiPUVwQb1CPc7NaS5eM=
